app = "nikhilvaidyanath"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  API_HOST = "0.0.0.0"
  API_PORT = "8000"
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  DEBUG = "false"
  GEMINI_MODEL = "gemini-2.5-flash"
  LLM_TEMPERATURE = "0.0"
  LLM_MAX_TOKENS = "3072"
  EMBEDDING_MODEL = "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
  EMBEDDING_BATCH_SIZE = "128"
  MAX_FILE_SIZE_MB = "50"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
