[phases.setup]
nixPkgs = ["python310", "tesseract", "ghostscript", "gcc"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p data uploads logs cache data/faiss_index"
]

[start]
cmd = "python main.py"
